### ISSUE TITLE
Change repo summary wiki link 

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-macros#10]
`http://www.freecadweb.org/wiki/index.php?title=Macros_recipes`
to
`http://www.freecadweb.org/wiki/Macros_recipes`

**Comment by luzpaz** [comment]
@galou ping

**Comment by galou** [comment]
Cf. 9a01d3c. Is that what you meant?

**Comment by luzpaz** [comment]
@galou No but thanks nonetheless :smile: 

What I meant was:  
![repo-summary](https://user-images.githubusercontent.com/4140247/43676091-54eb3226-97b8-11e8-8d0d-601ba7927755.png)

**Comment by galou** [comment]
Sorry, I should have analyzed the issue title more in details.

I actually don't know how to do it. The fact that it isn't obvious is maybe related to the fact that the repository owner is @FreeCAD/core-developers. Maybe one of them will do it.

**Comment by bblacey** [comment]
Done
