### ISSUE TITLE
Please add circle support

### ISSUE THREAD

**Issue by Goodfeat** [FreeCAD/FreeCAD-macros#109]
Hello, 
Thank you for creating this wonderful script.

there is a request, could you please add circle support.

I tried to modify the script of the previous version.
the your latest version is quite unstable and the results are unpredictable

I used the previous version where you could manually add values, and also tried to implement additional options for disabling binding and reverse. the creation of two directions at the same time was also added.
the script is still incomplete and has some bugs

However, the main disadvantage is the inability to create an offset from the circle. 

Could you help add circle offsets or at least give me a hint
[OffsetInSketcherPlus.zip](https://github.com/FreeCAD/FreeCAD-macros/files/7199913/OffsetInSketcherPlus.zip)

**Comment by galou** [comment]
@edi271 can you please have a look at this? Thanks!

**Comment by edi271** [comment]
Hello Goodfeat,
please open a thread for discussing the issue in the FreeCAD forum. I do not understand, what you mean with "an offset from the cicle"

**Comment by Goodfeat** [comment]
![image](https://user-images.githubusercontent.com/44455128/134277422-f4268db1-b5e2-4f95-aa79-ac9ceb603371.png)
I mean, a macro cannot create offsets for circles

![image](https://user-images.githubusercontent.com/44455128/134277261-dc116a4c-c137-4b3e-b3f7-9541bfab1d2f.png)

Apparently the script is trying to find the starting point, but it is not in the circle

p.s I will duplicate this topic in the next branch

**Comment by galou** [comment]
Any update on this?

Otherwise I'll close the ticket.

**Comment by edi271** [comment]
Please close the ticket
