### ISSUE TITLE
Please UNDO in Compartments

### ISSUE THREAD

**Issue by sysmaya** [FreeCAD/FreeCAD-macros#116]
After creating a division, Me usually make a mistakes. Please add Undo.

**Comment by luzpaz** [comment]
This ticket makes no sense and sufferers from a lack of investment in detail. Is it reporting an issue with a specific macro? if so, which one? And if not, why is the ticket erroneously being opened in this repository? Beside, what version of FreeCAD is being used? Full [About](https://wiki.freecad.org/About) info? Is there a step by step reproduction of the issue?

Please post to the forum next time. Closing ticket.
