### ISSUE TITLE
Unable to fetch some Macros

### ISSUE THREAD

**Issue by Jee-Bee** [FreeCAD/FreeCAD-macros#12]
Some of the macros are unable to download from the 0.17 workbench/ macro downloader. First noticed with the DeepCopy macro see https://forum.freecadweb.org/viewtopic.php?f=18&t=27537&start=10#p229653
But also noticed with others

**Comment by galou** [comment]
The ability of the Add-on manager to download code from github requires:
- a specific markup in the Wiki
- the handling of this markup by the Add-on manager.

Nothing can be done about it in this repository.
