### ISSUE TITLE
FCC Circular Text installation fails

### ISSUE THREAD

**Issue by sslupsky** [FreeCAD/FreeCAD-macros#132]
Attempting to install the FCCCircularText macro reports an error:

![Screen Shot 2022-04-28 at 10 42 48 AM](https://user-images.githubusercontent.com/16888734/165802830-41a41274-c877-403d-b984-04169b683c30.png)

This may be related to issue #111 (regression?)

```
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.28765 (Git)
Build type: Release
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: C/Default (C)
Installed mods: 
  * kicadStepUpMod 10.10.4
```

**Comment by galou** [comment]
Installation worked for me from the Addon Manager on 
```
OS: Ubuntu 20.04.5 LTS (i3/i3)
Word size of FreeCAD: 64-bit
Version: 0.21.
Build type: Release
Branch: unknown
Hash: 49e37dd611ef5093b4084720ace7c5d963ccf7c9
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.2
Locale: English/United States (en_US)
Installed mods: 
  * SearchBar 1.0.1
  * MeshRemodel 1.8919.0
```

I'll close the issue if you don't confirm you still have the problem.

**Comment by luzpaz** [comment]
Closing. If issue persists please re-open
