### ISSUE TITLE
[3D Generator] Something else?

### ISSUE THREAD

**Issue by 18turbo** [FreeCAD/FreeCAD-macros#142]
Hello,

When does the new added macro appear in the Addon Manager?.

Do I have to do something else?

Regards

**Comment by luzpaz** [comment]
You have to update the addon manager cache, it should appear after that

**Comment by luzpaz** [comment]
Closing. Please re-open if an issue presents

**Comment by 18turbo** [comment]
Hello @luzpaz ,

I update the Addon Manager cache and it doesn't work. Since the Merged was done I'm trying and I don't see it.

That's why I asked

Regards

**Comment by luzpaz** [comment]
I can't check ATM. @galou can u confirm?

**Comment by chennes** [comment]
It's showing fine for me -- make sure you're searching for it by its filename ("G3D").p

**Comment by 18turbo** [comment]
Everyone I ask tells me they don't see it

**Comment by 18turbo** [comment]
it works fine. In Linux, you must have installed Gitpyhton ;)

Thanks for all!
