### ISSUE TITLE
airfoil import and scale Doesn't work on linux

### ISSUE THREAD

**Issue by warriorman8** [FreeCAD/FreeCAD-macros#166]
As described in the title and when attempting to run it says:
<class 'AttributeError'>: 'PySide2.QtCore.QCoreApplication' object has no attribute 'activeWindow'

**Comment by galou** [comment]
The title doesn't mention any macro.

**Comment by jpretori** [comment]
I run Arch and am happy to help test. When I search the Addon manager for "airfoi" I get these results. Which of them are we talking about?

![2024-08-09_scrot](https://github.com/user-attachments/assets/b880341d-2d07-456e-8ca0-a0c551149f02)

**Comment by jpretori** [comment]
> import and scale (second)

Thanks @warriorman8. Please will you attach the .dat file you use when encountering the problem?

**Comment by jpretori** [comment]
OK I tried to import this. 

I was unable to even see the file in the load dialog until I changed its extension to .dat. So I did that. 

1. I renamed the file to aerofoil.dat so the dialog box could see it
2. Made the chord length 100
3. Left the radio button on DWire

I get this error message in the Report view:

> 10:29:17  /home/johan/.local/share/FreeCAD/Macro/Airfoil_Import_&_Scale.FCMacro:89: DeprecationWarning: 'exec_' will be removed in the future. Use 'exec' instead.
>   self.dialog.exec_()
> 10:29:19  Error, not a valid .dat file

This is the same as I got for the other .dat files I tried. 

So I fiddled around with the macro itself, and made it import the traceback module & print out more complete exception details. Here is the message it ended up giving:

> 10:49:02  Error, not a valid .dat file
> 10:49:54  <string>(1)<class 'SyntaxError'>: '(' was never closed (Airfoil_Import_&_Scale.FCMacro, line 77)
> 10:50:16  Error, not a valid .dat file
> 10:50:16  Traceback (most recent call last):
> 10:50:16    File "/home/johan/.local/share/FreeCAD/Macro/Airfoil_Import_&_Scale.FCMacro", line 103, in proceed
> 10:50:16      importAirfoilDAT.insert(f1,"Unnamed")
> 10:50:16    File "/usr/lib/freecad/Mod/Draft/importAirfoilDAT.py", line 106, in insert
> 10:50:16      obj = process(filename)
> 10:50:16            ^^^^^^^^^^^^^^^^^
> 10:50:16    File "/usr/lib/freecad/Mod/Draft/importAirfoilDAT.py", line 136, in process
> 10:50:16      afile = pythonopen(filename, 'r')
> 10:50:16              ^^^^^^^^^^
> 10:50:16  NameError: name 'pythonopen' is not defined
> 10:50:16  
> 10:50:16  During handling of the above exception, another exception occurred:
> 10:50:16  
> 10:50:16  Traceback (most recent call last):
> 10:50:16    File "/home/johan/.local/share/FreeCAD/Macro/Airfoil_Import_&_Scale.FCMacro", line 113, in proceed
> 10:50:16      traceback.print_exception(sys.exc_info())
> 10:50:16    File "/usr/lib/python3.12/traceback.py", line 123, in print_exception
> 10:50:16      value, tb = _parse_value_tb(exc, value, tb)
> 10:50:16                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 10:50:16    File "/usr/lib/python3.12/traceback.py", line 104, in _parse_value_tb
> 10:50:16      raise TypeError(f'Exception expected for value, '
> 10:50:16  TypeError: Exception expected for value, tuple found
> 

Seems like the importAirfoilDAT module has some problem.

@galou could you please give some help at this point? Searching Github it seems like this is somehow part of Freecad? How do we proceed from here?

**Comment by galou** [comment]
> import and scale (second)

It's stated that the second item on the list is from the wiki and the third is from git. Someone should update the git version (@quick61) .

**Comment by galou** [comment]
The error mentioned by @jpretori  was changed (fixed?) with https://github.com/FreeCAD/FreeCAD/commit/ff11cd25ee99b5e959616f3805f0d9bfd3a0be76.

I was able to import the file above but I have the impression that the "Chord Length" parameter doesn't do anything. I also get the error message "Error, not a valid .dat file" though.

**Comment by jpretori** [comment]
I fiddled with it some more, but got nowhere. I'm willing to help, but don't know what to do. So for now I'm going to leave it alone until someone suggest something specific that might be helpful :)
