### ISSUE TITLE
Making View Rotation Macro work with floats

### ISSUE THREAD

**Issue by fatihyaman661** [FreeCAD/FreeCAD-macros#170]
I am really noob how to use git, so I couldn't manage to commit this myself. However in Puregui/viewRotation.FCMacro line 237, the entered value is changed into an integer. I couldn't see a reason to make this an integer. I have downloaded the macro and changed this line into

value = float(self.line_edits[i].text())

The code worked flawlessly and I was able to input float values as well. With this simple change the macro can be made much better.

**Comment by galou** [comment]
Cf. f523b54. Please test.
