### ISSUE TITLE
Mistakes in the "How to submit a macro" instructions

### ISSUE THREAD

**Issue by goatchurchprime** [FreeCAD/FreeCAD-macros#44]
* Everywhere it references "FreeCAD-addons" should probably be "FreeCAD-macros"

* Needs to say "cd FreeCAD-macros" after the "Clone your fork locally..." line

* Link in "Follow our [guidelines]..." is broken.

**Comment by luzpaz** [comment]
Thanks. Care to submit a PR ?

**Comment by galou** [comment]
Documentation updated. Thanks!
