### ISSUE TITLE
Change http:// to https:// in repo description name

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-macros#49]
![image](https://user-images.githubusercontent.com/4140247/59194518-4191ca80-8b57-11e9-83ab-815efe14e31d.png)

**Comment by galou** [comment]
@yorikvanhavre or someone else with permissions, please.

Also, I'd like to change the description. I'd like this repository to contain only peer-reviewed macros and not to be a just a place where people can put macros instead of pasting the code in the wiki.

**Comment by luzpaz** [comment]
@kkremitzki do you have permissions to do this, perhaps?

**Comment by kkremitzki** [comment]
I've just updated it.

**Comment by luzpaz** [comment]
sweet! thanks man.
