### ISSUE TITLE
Discussion: the utility of the wiki macros

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-macros#67]
Discussion on why we have the wiki macros in gists.  
Why? It seems there was an issue that was encountered which influenced moving to this 'gist' fix.  

* Examples:
  * https://forum.freecadweb.org/viewtopic.php?f=22&t=39188
  * https://forum.freecadweb.org/viewtopic.php?f=3&t=39354&p=334389#p334321
* Problems with gists: 
  * not easily browesable 
  * jumping through a lot of hoops to get to (go to wiki page, expand macro, copy gist url, no line numbers to reference)
  * gists have multiple versions (though the latest is shown, but could be confusing)
  * raw gists don't have line numbers that are linkable
  * gist URL is long and esoteric
  * how do users know who mario52 is if they look at the http logs (better for it to be under the FreeCAD org umbrella)
  * difficult to submit fixes and refinements to
  * difficult to organize

**Comment by galou** [comment]
I didn't check what you write but I guess you're right about limitations of gist. What do you think about opening a new repository for macros of the wiki?
As I wrote in https://github.com/FreeCAD/FreeCAD-macros/issues/49#issuecomment-501576412, I'd like to keep this repository as clean as possible (though I have to admit that I'm not completely satisfied about the current state and I'm thinking of deleting macros with low quality or little use).

The second repository (for example named `wiki-macros`) would be just a place where to put macros for storage. Maintainers would just accept pull request without review. The only thing I would do (I count myself as a potential maintainer) would be to create directories corresponding to the categories of the macros in the wiki.

**Comment by luzpaz** [comment]
hmm...I'm thinking we need more feedback from the community on this. As FC grows we do need to have a way to vet macros we offer people. For example, Arch Linux has Arch Packages and then has the Arch User Packages or AUR. There are a lot more AUR packages then there are Arch Packages, and they aren't strictly vetted with a forewarning about that. So it sounds like that is what you're proposing?

**Comment by galou** [comment]
Closed because of lack of activity.
