### ISSUE TITLE
screw maker1 2

### ISSUE THREAD

**Issue by TedescoAntonio** [FreeCAD/FreeCAD-macros#72]
hello, I loaded your library from the freecad addons but when I run it nothing happens. Freecad version 0.18

**Comment by luzpaz** [comment]
@TedescoAntonio please report this on the FreeCAD Python Scripting subforum: https://forum.freecadweb.org/viewforum.php?f=22  
Make sure to follow the [forum guidelines](https://forum.freecadweb.org/viewtopic.php?f=3&t=2264)

**Comment by luzpaz** [comment]
@TedescoAntonio did you open a thread? if so please report back

**Comment by galou** [comment]
Closed because of lack of activity.
