### ISSUE TITLE
BoxCreator overhangTopBack is set to overhangTopRight

### ISSUE THREAD

**Issue by spanner888** [FreeCAD/FreeCAD-macros#74]
Create a box, with defaults, except set overhangTopRight to some value and box will ALSO have a top back overhang.

See BoxCreator.FCMacro lines: 59:62
        overhangTop = [self.form.overhangTopLeft.value(),
                       self.form.overhangTopRight.value(),
                       self.form.overhangTopFront.value(),
                       self.form.overhangTopRight.value()]
last line should read 
                       self.form.overhangTopBack.value()]

**Comment by luzpaz** [comment]
@spanner888 please always include your ```Help -> 'About FreeCAD'```
 
CC @chbergmann

**Comment by galou** [comment]
Fixed in #75
