### ISSUE TITLE
Addon manager forever loop reading wiki

### ISSUE THREAD

**Issue by angerangel** [FreeCAD/FreeCAD-macros#85]
Hello, this bug affect windows and Linux version of Freecad 0.18. 

If you activate the addons manager, clicking on Marcos tab, it starts reading Wiki, but it **never stops reading** and you can't do anything except close the addons manager. So **you can't install any addons.**

**Comment by luzpaz** [comment]
Please close this ticket in favor of https://github.com/FreeCAD/FreeCAD-addons/issues/176
