### ISSUE TITLE
Issues with macros

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-macros#9]
Please see https://forum.freecadweb.org/viewtopic.php?f=10&t=26491

**Comment by galou** [comment]
I'm not convinced this is a problem with this repository. The mentioned topic relates to the add-on manager/macro installer.
A solution would be to have a special markup for external macro code in the wiki so that macros with this markup can be installed through the add-on manager.

**Comment by galou** [comment]
Suggestion done at https://forum.freecadweb.org/viewtopic.php?f=21&t=26540.
